#!/bin/bash

PYFILE=$PYFILE

if [ -z "$PYFILE" ]; then
	echo "Error: PYFILE environment variable is no set."
	exit 1
fi

if [ ! -f "$PYFILE" ]; then
	echo "Error: file $PYFILE not found."
	exit 1
fi

python3 "$PYFILE"
